### PR TITLE
ToLiss A319 MCDU screen and fullscreen on secondary display

### PR DESCRIPTION
**Pull request by dsp0x4**

### CODE REVIEW

**Comment by waynepiekarski** [comment]
Thank you for your submission. Can you break this up into two commits so they are separable? I can also do this for you, but then you'll lose credit for the commits.

**Comment by dsp0x4** [comment]
Sure! I'll do that.

**Comment by dsp0x4** [comment]
Is this ok? Do you need also 2 pull requests?

**Comment by waynepiekarski** [comment]
The commits are correctly separated now, but you didn't put your name on it. Right now it just says "Your Name".

**Comment by dsp0x4** [comment]
Ok, I didn't notice that, I'll fix it right now.

**Comment by dsp0x4** [comment]
I made a mess, I'm not so expert. I'm working on it.

**Comment by dsp0x4** [comment]
I'll make a new request

**Pull request closed without merging**
